# Generated by Django 4.2 on 2024-11-22 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faculty.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dean', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', validators=[faculty.validators.validate_size_and_type])),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('Personal Data Sheet', 'Personal Data Sheet'), ('Syllabi', 'Syllabi'), ('Class Records', 'Class Records'), ('Grading Sheets', 'Grading Sheets'), ('Accomplishment Report', 'Accomplishment Report'), ('Exams', 'Exams'), ('Quizzes/Tests', 'Quizzes/Tests'), ('Table of Specifications', 'Table of Specifications'), ('Rubrics', 'Rubrics'), ('Sample Student Project', 'Sample Student Project'), ('Instructional Materials', 'Instructional Materials'), ('PRC License', 'PRC License'), ('Trainings/Seminars', 'Trainings/Seminars'), ('Research Projects', 'Research Projects'), ('Extension Projects', 'Extension Projects'), ('Documentation', 'Documentation'), ('Membership in Organization', 'Membership in Organization')], max_length=100)),
                ('document_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dean.department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dean.program')),
                ('submission_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.submissionbin')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
