# Generated by Django 5.1.3 on 2024-12-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(max_length=100),
        ),
    ]
