# Generated by Django 4.2 on 2024-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
