# Generated by Django 5.1.3 on 2024-12-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dean", "0002_customuser_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="program",
        ),
        migrations.AddField(
            model_name="customuser",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dean.program",
            ),
        ),
    ]
