# Generated by Django 5.1.3 on 2024-12-06 11:55

import faculty.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qaofile",
            name="file",
            field=models.FileField(
                upload_to="documents/",
                validators=[faculty.validators.validate_size_and_type],
            ),
        ),
    ]
