# Generated by Django 5.1.3 on 2024-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qao", "0002_alter_qaofile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="qaofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
